studybub:
  image:
    repository: ghcr.io/subtoferalsloth11/studybub
    pullPolicy: Always
  config:
    STUDYBUB_DB_PATH: /data/data.db
  persistence:
    enabled: true
    existingClaim: studybub-studybub-data
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: studybub.syntaxrewrite.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: studybub-tls
      hosts:
        - studybub.syntaxrewrite.com
