{{- if .Values.studybub.secretConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-studybub-secret
  labels:
    {{- include "studybub.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.studybub.secretConfig }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
