apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-studybub
  labels:
    {{- include "studybub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.studybub.service.type | quote }}
  ports:
    - port: {{ .Values.studybub.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8000
      targetPort: browserquest
      protocol: TCP
      name: browserquest
  selector:
    {{- include "studybub.selectorLabels" . | nindent 4 }}
