import katex from "katex";
import { useMemo } from "react";

interface MathTextProps {
  /** The TeX source to typeset. */
  tex: string;
  /** Readable plain-text shown if typesetting fails (FR-012). */
  fallback: string;
  /** Render as a centred display equation rather than inline. */
  display?: boolean;
}

/**
 * Renders a piece of mathematical notation with KaTeX, degrading to a readable
 * plain-text fallback when the source cannot be typeset.
 *
 * KaTeX emits MathML alongside its visual output, so screen readers announce the
 * notation; the plain-text fallback keeps content legible if rendering throws.
 *
 * @param props - The component props.
 * @param props.tex - The TeX source to typeset.
 * @param props.fallback - Plain text shown when typesetting fails.
 * @param props.display - Whether to render as a centred display equation.
 * @returns The typeset maths, or a plain-text fallback span.
 */
export function MathText({
  tex,
  fallback,
  display = false,
}: Readonly<MathTextProps>) {
  const html = useMemo(() => {
    try {
      return katex.renderToString(tex, {
        displayMode: display,
        throwOnError: true,
        output: "htmlAndMathml",
      });
    } catch {
      console.warn(`StudyBub: could not typeset "${tex}"; showing fallback.`);
      return null;
    }
  }, [tex, display]);

  if (html === null) {
    return <span className="font-body text-ink">{fallback}</span>;
  }

  return (
    <span
      className={display ? "my-2 block text-center" : "inline-block"}
      // KaTeX output is generated by a trusted library from authored content.
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
