#!/usr/bin/env bash
#
# provision-vps.sh - Provision a fresh Ubuntu VPS for StudyBub deployments.
#
# This script installs all dependencies, creates the studybub system user,
# sets up directories with correct ownership, generates application secrets,
# writes the systemd unit and nginx config, obtains a TLS certificate via
# certbot, and starts the service.
#
# Usage:
#   sudo bash provision-vps.sh
#
# Prerequisites:
#   - Ubuntu 22.04 or 24.04.
#   - nginx installed (the script will install it if missing).
#   - A DNS A/AAAA record pointing studybub.syntaxrewrite.com to this VPS.
#   - Ports 80 and 443 reachable from the internet (for certbot).
#
# @author John Grimes

set -euo pipefail

readonly APP_DIR="/opt/studybub"
readonly DATA_DIR="/var/lib/studybub"
readonly APP_USER="studybub"
readonly DOMAIN="studybub.syntaxrewrite.com"
readonly NODE_ENV="production"

echo "=== StudyBub VPS Provisioning ==="
echo ""

# ---------------------------------------------------------------------------
# 1. Install system dependencies.
# ---------------------------------------------------------------------------
echo "--- Installing system dependencies ---"

export DEBIAN_FRONTEND=noninteractive
sudo apt-get update -qq

if ! command -v nginx &>/dev/null; then
  echo "Installing nginx..."
  sudo apt-get install -y -qq nginx
fi

if ! command -v certbot &>/dev/null; then
  echo "Installing certbot..."
  sudo apt-get install -y -qq certbot python3-certbot-nginx
fi

if ! command -v curl &>/dev/null; then
  sudo apt-get install -y -qq curl
fi

if ! command -v unzip &>/dev/null; then
  sudo apt-get install -y -qq unzip
fi

# ---------------------------------------------------------------------------
# 2. Install Bun.
# ---------------------------------------------------------------------------
echo ""
echo "--- Installing Bun ---"
# Install Bun system-wide into /opt/bun rather than a user's $HOME. A home
# install is not traversable by the studybub service user, by systemd, or by
# non-interactive SSH sessions (which never source that home's shell rc), so
# both the service and deploys fail with "bun: command not found".
readonly BUN_INSTALL_DIR="/opt/bun"

if [ ! -x /usr/local/bin/bun ]; then
  sudo rm -rf "$BUN_INSTALL_DIR"
  sudo mkdir -p "$BUN_INSTALL_DIR"
  sudo chown -R "$USER:$USER" "$BUN_INSTALL_DIR"

  # The installer honours BUN_INSTALL to choose the destination directory.
  BUN_INSTALL="$BUN_INSTALL_DIR" curl -fsSL https://bun.sh/install | bash

  # Take ownership as root and expose read/execute to every user so the
  # studybub service account, systemd, and non-interactive SSH sessions can
  # all run bun.
  sudo chown -R root:root "$BUN_INSTALL_DIR"
  sudo chmod -R a+rX "$BUN_INSTALL_DIR"
  sudo ln -sf "$BUN_INSTALL_DIR/bin/bun" /usr/local/bin/bun
fi

bun --version
echo "Bun installed."

# ---------------------------------------------------------------------------
# 3. Create the studybub system user and group.
# ---------------------------------------------------------------------------
echo ""
echo "--- Creating studybub user and group ---"

if ! id -u "$APP_USER" &>/dev/null; then
  sudo useradd --system --user-group --create-home --shell /bin/bash "$APP_USER"
  echo "User '$APP_USER' created."
else
  echo "User '$APP_USER' already exists."
fi

# ---------------------------------------------------------------------------
# 4. Create application and data directories with correct ownership.
# ---------------------------------------------------------------------------
echo ""
echo "--- Creating directories ---"

sudo mkdir -p "$APP_DIR"
sudo mkdir -p "$DATA_DIR"

sudo chown "$APP_USER:$APP_USER" "$APP_DIR"
sudo chown "$APP_USER:$APP_USER" "$DATA_DIR"
sudo chmod 750 "$APP_DIR"
sudo chmod 750 "$DATA_DIR"

echo "Directories created and permissions set."

# ---------------------------------------------------------------------------
# 5. Generate secrets and write the .env file.
# ---------------------------------------------------------------------------
echo ""
echo "--- Generating secrets ---"

ENV_FILE="$APP_DIR/.env"

# Only generate secrets if the .env file does not already exist so that
# re-running the provisioning script does not overwrite existing keys.
if [ ! -f "$ENV_FILE" ]; then
  SESSION_SECRET=$(openssl rand -hex 32)
  ENCRYPTION_KEY=$(openssl rand -hex 32)

  sudo tee "$ENV_FILE" > /dev/null <<EOF
# StudyBub environment - auto-generated by provision-vps.sh.
# Do not commit this file to version control.
SESSION_SECRET=$SESSION_SECRET
ENCRYPTION_KEY=$ENCRYPTION_KEY
STUDYBUB_DB_PATH=$DATA_DIR/data.db
NODE_ENV=$NODE_ENV
EOF

  sudo chown "$APP_USER:$APP_USER" "$ENV_FILE"
  sudo chmod 600 "$ENV_FILE"

  echo "Secrets generated and written to $ENV_FILE:"
  echo "  SESSION_SECRET=${SESSION_SECRET:0:8}..."
  echo "  ENCRYPTION_KEY=${ENCRYPTION_KEY:0:8}..."
  echo "  STUDYBUB_DB_PATH=$DATA_DIR/data.db"
  echo "  NODE_ENV=$NODE_ENV"
else
  echo ".env file already exists at $ENV_FILE - skipping secret generation."
fi

# ---------------------------------------------------------------------------
# 6. Create the systemd unit.
# ---------------------------------------------------------------------------
echo ""
echo "--- Creating systemd unit ---"

SYSTEMD_UNIT="/etc/systemd/system/studybub.service"

sudo tee "$SYSTEMD_UNIT" > /dev/null <<EOF
[Unit]
Description=StudyBub learning application
After=network.target

[Service]
Type=simple
User=$APP_USER
Group=$APP_USER
WorkingDirectory=$APP_DIR
EnvironmentFile=$APP_DIR/.env
Environment=NODE_ENV=$NODE_ENV
ExecStart=/usr/local/bin/bun run $APP_DIR/scripts/server.ts
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

echo "Systemd unit written to $SYSTEMD_UNIT."

sudo systemctl daemon-reload
sudo systemctl enable studybub.service

echo "Systemd unit enabled."

# ---------------------------------------------------------------------------
# 6b. Allow the studybub user to restart its own service.
# ---------------------------------------------------------------------------
# The CI deploy reloads the app over SSH as the studybub user, which has no
# password and therefore cannot run sudo interactively. Grant it passwordless
# restart rights scoped to this single service.
# ---------------------------------------------------------------------------
readonly SUDOERS_FILE="/etc/sudoers.d/studybub"
sudo tee "$SUDOERS_FILE" >/dev/null <<EOF
studybub ALL=(root) NOPASSWD: /usr/bin/systemctl restart studybub.service
EOF
sudo chmod 0440 "$SUDOERS_FILE"

# Validate the sudoers file before trusting it; abort if malformed.
sudo visudo -cf "$SUDOERS_FILE"

echo "Sudoers entry granted for service restart."

# ---------------------------------------------------------------------------
# 7. Configure nginx.
# ---------------------------------------------------------------------------
echo ""
echo "--- Configuring nginx ---"

NGINX_SITE="/etc/nginx/sites-available/studybub"
NGINX_ENABLED="/etc/nginx/sites-enabled/studybub"

sudo tee "$NGINX_SITE" > /dev/null <<EOF
# StudyBub nginx site - reverse proxy to the Bun server.
server {
    # Listen on both IPv4 and IPv6 so the ACME HTTP-01 challenge is reachable
    # over both address families. Without the [::] listener, IPv6 connections
    # fall through to another server block and the challenge fails.
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

# Enable the site if not already enabled.
if [ ! -L "$NGINX_ENABLED" ]; then
  sudo ln -sf "$NGINX_SITE" "$NGINX_ENABLED"
  echo "Nginx site enabled."
else
  echo "Nginx site already enabled."
fi

# Test the configuration before reloading.
sudo nginx -t

sudo systemctl reload nginx
echo "Nginx reloaded."

# ---------------------------------------------------------------------------
# 8. Obtain TLS certificate via certbot.
# ---------------------------------------------------------------------------
echo ""
echo "--- Obtaining TLS certificate ---"

if ! sudo certbot certificates 2>/dev/null | grep -q "$DOMAIN"; then
  sudo certbot --nginx \
    -d "$DOMAIN" \
    --non-interactive \
    --agree-tos \
    --email "john@grimes.id.au" \
    --redirect
  echo "TLS certificate obtained for $DOMAIN."
else
  echo "TLS certificate already exists for $DOMAIN."
fi

# ---------------------------------------------------------------------------
# 9. Start the service (it will fail gracefully until the first deploy).
# ---------------------------------------------------------------------------
echo ""
echo "--- Starting service ---"

if sudo systemctl is-active --quiet studybub.service; then
  sudo systemctl restart studybub.service
  echo "Service restarted."
else
  # Start the service - it will fail if no build has been deployed yet,
  # which is expected and harmless.
  sudo systemctl start studybub.service 2>/dev/null || true
  echo "Service start attempted (may fail until first deploy - this is normal)."
fi

echo ""
echo "=== Provisioning complete ==="
echo ""
echo "  Application: $APP_DIR"
echo "  Data:        $DATA_DIR"
echo "  Service:     studybub.service"
echo "  URL:         https://$DOMAIN"
echo ""
echo "The service will serve the app after the first deploy via GitHub Actions."
